main/urls.py
from django.urls import path, include
from .views import index, RegisterView, UpdateProfile, ListNotes, CreateNote, UpdateNote, DeleteNote, NoteViewSet
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'note', NoteViewSet)
print(router.urls)

app_name = 'main'

urlpatterns = (
        [
            path('api/', include(router.urls)),
            path('login/', LoginView.as_view(template_name='main/login.html'), name='login'),
            path('logout/', LogoutView.as_view(next_page='main:index'), name='logout'),
            path('register/', RegisterView.as_view(), name='register'),
            path('note/<int:pk>/update/', UpdateNote.as_view(), name='update_note'),
            path('note/<int:pk>/delete/', DeleteNote.as_view(), name='delete_note'),
            path('profile/<int:pk>/create_note/', CreateNote.as_view(), name='create_note'),
            path('profile/<int:pk>/', UpdateProfile.as_view(), name='update_profile'),
            path('profile/<int:pk>/notes/', ListNotes.as_view(), name='list_notes'),
            path('', index, name='index'),

        ]
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

)

myWiki/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

COLOR_CHOICES = [
    ('MediumSeaGreen', 'Зеленый'),
    ('PaleVioletRed', 'Красный'),
    ('Khaki', 'Желтый'),
    ('Plum', 'Фиолетовый'),
    ('SkyBlue', 'Синий'),
    ('LightSlateGray', 'Серый'),
]


class Note(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    text = models.TextField(blank=True, null=True, max_length=300)
    theme = models.ForeignKey('Theme', blank=True, null=True, related_name='notes', on_delete=models.CASCADE,
                              verbose_name='Тема')
    author = models.ForeignKey('Profile', blank=True, null=True, related_name='notes', on_delete=models.CASCADE,
                               verbose_name='Автор')
    importance = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)],
                                     verbose_name='Важность')
    color = models.CharField(max_length=30, choices=COLOR_CHOICES, default='green', verbose_name='Цвет')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, verbose_name='Запись активна')

    class Meta:
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'
        ordering = ['importance', '-created']

    def __str__(self):
        return self.title

    def soft_delete(self):
        self.is_active = False
        self.save()


class Theme(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название темы')

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'

    def __str__(self):
        return self.title

    def count_notes(self):
        return self.notes.count()


class Profile(models.Model):
    def validate_image(fieldfile_obj):
        file_size = fieldfile_obj.file.size
        megabyte_limit = 150.0
        if file_size > megabyte_limit * 1024 * 1024:
            raise ValidationError(
                "Максимальный размер файла {}MB".format(str(megabyte_limit))
            )

    user = models.OneToOneField(
        User, unique=True, on_delete=models.CASCADE, related_name="profile"
    )

    username = models.CharField(
        default="-------",
        max_length=50,
        verbose_name="Имя пользователя",
        blank=True,
        null=True,
        unique=False,
    )

    avatar = models.ImageField(
        upload_to="catalog/files/",
        null=True,
        validators=[validate_image],
        default="catalog/files/ava-default.png",
    )

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили пользователей"

    def __str__(self):
        return self.username

    def count_notes(self):
        return self.notes.count()

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Profile, Note


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100, help_text="имя пользователя")
    password = forms.CharField(required=True, help_text="пароль")


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'avatar',)


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'text', 'theme', 'importance', 'color')

main/views.py
from django.shortcuts import render
from .forms import *
from django.views import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.urls import reverse
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from .serializers import NoteSerializer
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend


class NoteViewSet(viewsets.ModelViewSet):
    queryset = Note.objects.all()
    serializer_class = NoteSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['title', 'importance']
    basename = 'Note'


def index(request):
    context = {}
    context['themes'] = Theme.objects.all()
    return render(request, 'main/index.html', context=context)


class RegisterView(View):
    def get(self, request):
        form = RegisterForm
        return render(request, 'main/register.html', {"form": form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = User.objects.create_user(username=username)
                user.set_password(password)
                user.save()
                login(request, user)
                profile = Profile.objects.create(
                    user=user,
                    username=username,
                )
                profile.save()
                return redirect("/")
            except IntegrityError:
                form.add_error("login", "Пользователь с таким логином уже существует")

        return render(request, "main/register.html", {"form": form})


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "main/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.get(pk=self.request.user.profile.pk)
        context['button_value'] = "Обновить профиль"
        context['themes'] = Theme.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy("main:index")


class ListNotes(ListView):
    template_name = 'main/list-notes.html'
    context_object_name = 'notes'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['themes'] = Theme.objects.all()
        return context

    def get_queryset(self):
        theme_params = self.request.GET.get('theme')
        if theme_params:
            return Note.objects.filter(author=self.request.user.profile, is_active=True, theme__title=theme_params)
        else:
            return Note.objects.filter(author=self.request.user.profile, is_active=True)


class CreateNote(CreateView):
    template_name = 'main/create-note.html'
    form_class = NoteForm

    def get_success_url(self):
        return reverse('main:list_notes', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_value'] = "Создать"
        context['themes'] = Theme.objects.all()
        return context

    def form_valid(self, form):
        note = form.save(commit=False)
        note.author = self.request.user.profile
        note.save()
        return super().form_valid(form)


class UpdateNote(UpdateView):
    model = Note
    form_class = NoteForm
    template_name = "main/create-note.html"

    def get_success_url(self):
        return reverse('main:list_notes', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_value'] = "Обновить"
        context['themes'] = Theme.objects.all()
        return context


class DeleteNote(DeleteView):
    model = Note
    template_name = "main/create-note.html"

    def get_success_url(self):
        return reverse('main:list_notes', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['button_value'] = "Удалить"
        context['themes'] = Theme.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())

main/templates/layout/base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <title>
        {% block title %}Базовый шаблон{% endblock %}
    </title>
</head>
<body>
<header>
    <div class="bg-secondary">
        <div style="margin-left: 15%; margin-right: 10%">
            <div class="d-flex align-items-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item me-4">
                        <a href="/">
                            <img src="https://cdn-icons-png.flaticon.com/512/4632/4632151.png" width="100px"
                                 style="margin-left: 5%; margin-bottom: 2px;">
                        </a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="/">
                            <span class="text-white fs-5">Главная</span>
                        </a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:list_notes' pk=request.user.profile.pk %}">
                            <span class="text-white fs-5">Заметки</span>
                        </a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:note-list' %}">
                            <span class="text-white fs-5">Перейти к API</span>
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:update_profile' pk=request.user.profile.pk %}">
                            <span class="text-white fs-5">Профиль</span>
                        </a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:logout' %}">
                            <span class="text-white fs-5">Выход</span>
                        </a>
                    </li>
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <li class="list-inline-item me-4">
                        <a href="/admin/">
                            <span class="text-white fs-5">Административный раздел</span>
                        </a>
                    </li>
                    {% endif %}
                    {% else %}
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:login' %}">
                            <span class="text-white fs-5">Вход</span>
                        </a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="{% url 'main:register' %}">
                            <span class="text-white fs-5">Регистрация</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li class="list-inline-item me-4"><a
                            href="{% url 'main:update_profile' pk=request.user.profile.pk %}">
                        <img src="{{request.user.profile.avatar.url}}" width="100px"
                             style="border-radius: 50%; margin-left: 5%; margin-bottom: 2px; box-shadow: 0 0 10px 5px rgba(0, 255, 0, 0.5);"></a>
                    </li>
                    {% endif %}
                </ul>

            </div>

        </div>
    </div>
</header>
<hr>
<div class="container">
    <div class="row">
        <div class="col-2" style="background-color: #343a40; color: white;">
            <div style="display: flex; justify-content: center; margin-top: 15%">
                <ul style="list-style: none; padding: 0;">
                    {% if request.user.is_authenticated %}
                    {% for theme in themes %}
                    <li><a href="{% url 'main:list_notes' pk=request.user.profile.pk %}?theme={{theme.title}}"
                           style="font-size: 20px; color: white;">
                        {{ theme.title }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'main:list_notes' pk=request.user.profile.pk %}"
                           style="font-size: 20px; color: white;">
                        Все заметки</a></li>
                    {% else %}
                    {% for theme in themes %}
                    <li><a href="#"
                           style="font-size: 20px; color: white;">
                        {{ theme.title }}</a></li>
                    {% endfor %}
                    <li><a href="#"
                           style="font-size: 20px; color: white;">
                        Все заметки</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li style="margin-top: 10px;">
                        <button class="btn btn-success rounded">
                            <a href="{% url 'main:create_note' pk=request.user.profile.pk %}"
                               style="font-size: 20px; color: white; text-decoration: none;">Создать заметку</a>
                        </button>
                    </li>
                    {% else %}
                    <li style="margin-top: 10px;">
                        <button class="btn btn-success rounded">
                            <a href="{% url 'main:login' %}"
                               style="font-size: 20px; color: white; text-decoration: none;">Войти в профиль</a>
                        </button>
                    </li>
                    {% endif %}
                </ul>
            </div>


        </div>
        <div class="col-10" style="background-color: Silver; height: 780px;">
            {% block content %}
            <h1 style="text-align:center">Сайт для заметок!</h1>
            <p></p>
            <p></p>
            <p></p>
            <hr>
            <img src="https://img.freepik.com/free-psd/horizontal-banner-template-for-event-planner_23-2149072757.jpg?w=1380&t=st=1685768385~exp=1685768985~hmac=0a3ce3b771ed026d7cb08767f7bb4ad3c385d6d45668d6794f4f1c14031ac1e6"
                 width="100%" style="border-radius: 15px">
            {% endblock %}
        </div>
    </div>
</div>


</body>
</html>